# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool
  - gem install cocoapods -v '= 0.34.4'
  - cd Example && pod install && cd -
script:
- xctool test -workspace Example/CVKInfoBanner.xcworkspace -scheme CVKInfoBanner -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
